[package]
name = "notification"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
common = { path = "../../libs/common", features = ["http"] }
axum = { version = "0.8.8" }
